### POST /ingredients
POST http://localhost:3000/ingredients
Content-Type: application/json

{}

### GET /ingredients
GET http://localhost:3000/ingredients
Content-Type: application/json

### GET /ingredients/:id
GET http://localhost:3000/ingredients/1
Content-Type: application/json

### PUT /ingredients
PUT http://localhost:3000/ingredients
Content-Type: application/json

{
  "id": 1
}

### DELETE /ingredients/:id
DELETE http://localhost:3000/ingredients/1
Content-Type: application/json